openapi: 3.0.0
info:
  title: Connectify Nigeria Provider API
  version: 1.0.0
  description: API specification for Connectify Nigeria provider endpoints

servers:
  - url: http://localhost:8000
    description: Local development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Provider:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
          format: email
        business_name:
          type: string
        phone:
          type: string
        address:
          type: string
        services:
          type: array
          items:
            type: string
        rating:
          type: number
          format: float
        total_jobs:
          type: integer
        completed_jobs:
          type: integer
        total_revenue:
          type: number
          format: float

    Job:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [pending, accepted, in_progress, completed, cancelled]
        customer:
          $ref: '#/components/schemas/Customer'
        amount:
          type: number
          format: float
        created_at:
          type: string
          format: date-time

    Review:
      type: object
      properties:
        id:
          type: integer
        rating:
          type: integer
          minimum: 1
          maximum: 5
        comment:
          type: string
        customer:
          $ref: '#/components/schemas/Customer'
        created_at:
          type: string
          format: date-time
        provider_response:
          type: string

    Analytics:
      type: object
      properties:
        bookings:
          type: object
          properties:
            total:
              type: integer
            completed:
              type: integer
            pending:
              type: integer
        revenue:
          type: object
          properties:
            total:
              type: number
              format: float
            monthly:
              type: array
              items:
                type: object
                properties:
                  month:
                    type: string
                  amount:
                    type: number
                    format: float
        ratings:
          type: object
          properties:
            average:
              type: number
              format: float
            distribution:
              type: object
              properties:
                "1":
                  type: integer
                "2":
                  type: integer
                "3":
                  type: integer
                "4":
                  type: integer
                "5":
                  type: integer

paths:
  /api/providers/me:
    get:
      summary: Get provider profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Provider profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'

  /api/providers/me/stats:
    get:
      summary: Get provider statistics
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Provider statistics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_jobs:
                    type: integer
                  completed_jobs:
                    type: integer
                  total_revenue:
                    type: number
                    format: float
                  rating:
                    type: number
                    format: float

  /api/providers/me/jobs:
    get:
      summary: Get provider jobs
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [pending, accepted, in_progress, completed, cancelled]
      responses:
        '200':
          description: Provider jobs retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'

  /api/providers/me/jobs/{job_id}/status:
    put:
      summary: Update job status
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: job_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [accepted, in_progress, completed, cancelled]
      responses:
        '200':
          description: Job status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'

  /api/providers/me/reviews:
    get:
      summary: Get provider reviews
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Provider reviews retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'

  /api/providers/me/reviews/{review_id}/respond:
    post:
      summary: Respond to a review
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: review_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                response:
                  type: string
      responses:
        '200':
          description: Review response submitted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'

  /api/providers/me/analytics:
    get:
      summary: Get provider analytics
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: period
          schema:
            type: string
            enum: [week, month, year]
          default: month
      responses:
        '200':
          description: Provider analytics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Analytics' 